packaging_format = 2

id = "penpot"
name = "Penpot"

description.en = "Penpot - The Open-Source design &amp; prototyping platform "
description.fr = "Penpot - The Open-Source design &amp; prototyping platform "

version = "1.19.2~ynh1"

maintainers = ["orhtej2"]

[upstream]
license = "MPL-2.0"
website = "https://penpot.app/"

admindoc = "https://help.penpot.app/technical-guide/"
userdoc = "https://help.penpot.app/user-guide/"
code = "https://github.com/penpot/penpot"

[integration]
yunohost = '>= 11.2'
architectures = "amd64" # TODO : handle the "all" option (no ["all"])
multi_instance = true ldap = "false" # TODO : fixme, use actual booleans + handle the "not_relevant" value
sso = "true"
# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G... You may have have a look at CI results
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        # This will pre-fetch the asset which can then be deployed during the install/upgrade scripts with :
        #    ynh_setup_source --dest_dir="$install_dir"
        # You can also define other assets than "main" and add --source_id="foobar" in the previous command
        url = "https://github.com/penpot/penpot/archive/refs/tags/1.19.2.tar.gz"
        sha256 = "14de5b71f13f0fd542234f16fa5a307fbee7088bdfa343a53ff923b3f95f4edb"

        # These infos are used by https://github.com/YunoHost/apps/blob/master/tools/autoupdate_app_sources/autoupdate_app_sources.py
        # to auto-update the previous asset urls and sha256sum + manifest version
        # assuming the upstream's code repo is on github and relies on tags or releases
        # See the 'sources' resource documentation for more details

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    [resources.apt]
    packages = "postgresql redis  postgresql "[resources.database]
    type = "postgresql"